### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by dammysky** [vindicadi198/cool-compiler#1]
Hello Vindi,

Please I downloaded your code from  and I am trying to run it in eclipse but it could not duo to some missing classes like the main.cool.* please can you help to update the project with these files

**Comment by bunty2020** [comment]
Hi Dammysky,

All the main.cool.* classes are in the dist/cool.jar file. Just include that file as external library in eclipse.

**Comment by dammysky** [comment]
Hi bunty,

It is actually not available there(dist/cool.jar).
Thanks.

**Comment by bunty2020** [comment]
Hi Dammysky,

To compile the code just run make from project root folder. Cool.jar file gets compiled with make.

If you want to stick to eclipse then add the project as makefile project.

**Comment by dammysky** [comment]
This is the error i keep getting when i run it

Damilolas-MBP:~ damilolaibosiola$ /Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile ; exit;
make: *** empty variable name.  Stop.
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 2: OUT_JAR: command not found
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 3: fg: no job control
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 5: make_jar:: command not found
cp: directory ./dist does not exist
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 8: build:: command not found
make: *** No targets specified and no makefile found.  Stop.
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 9: -C: command not found
make: *** No targets specified and no makefile found.  Stop.
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 10: -C: command not found
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 13: clean:: command not found
make: *** No targets specified and no makefile found.  Stop.
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 14: -C: command not found
make: *** No targets specified and no makefile found.  Stop.
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 15: -C: command not found
/Users/damilolaibosiola/Documents/MscProject/Java/cool-compiler-master/Makefile: line 16: OUT_JAR: command not found
logout

[Process completed]

**Comment by dammysky** [comment]
Hi,

I have fixed it.
